#!/bin/sh
# Convert from go-style targets to their llvm equivalents with musl libc

set -euo pipefail

case "$1" in
	"linux/amd64")
		echo "x86_64-linux-musl"
		;;
	"linux/arm64")
		echo "aarch64-linux-musl"
		;;
	*)
		echo "Unsupported Target $1" >&2
		exit 1
esac

