FROM --platform=$BUILDPLATFORM node:23-alpine AS builder

WORKDIR /app/

COPY /muelli-frontend/ /app/

RUN npm ci

RUN npm run build


FROM --platform=$TARGETPLATFORM node:23-alpine

WORKDIR /app/

COPY --from=builder /app/server.js /app/
COPY --from=builder /app/helperfunctions /app/helperfunctions
COPY --from=builder /app/dist /app/dist
COPY --from=builder /app/node_modules /app/node_modules

EXPOSE 3000

CMD ["node", "server.js"]
