stages:
- test
- build
- deploy

test:
  stage: test
  image: gitlab.lrz.de:5005/sgc/muelli/gtest-runner:latest
  script:
  - cmake --preset ci-test .
  - cd build-ci
  - ninja
  - ./test/test_runner

build:
  stage: build
  image: espressif/idf:v5.3.1
  script:
  - idf.py build
  artifacts:
    paths:
    - build/muelli-iot.bin

deploy:
  stage: deploy
  image: curlimages/curl:8.11.0
  dependencies:
  - build
  script:
  - |
    curl --fail-with-body \
        --header "Job-Token: $CI_JOB_TOKEN" \
        --upload-file build/muelli-iot.bin \
        "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic/firmware/1.0.0/firmware.bin"
